version: "3"

services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=rascaloid

  api:
    image: kawasima/rascaloid:postgres
    environment:
      - JDBC_URL=jdbc:postgresql://db/rascaloid
      - JDBC_USER=rascaloid
      - JDBC_PASS=password
    depends_on:
      - db
  ui:
    image: kawasima/rascaloid-ri
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - RASCALOID_HOST=api
      - RASCALOID_PORT=3000
      - http_porxy=
    depends_on:
      - api
